from typing import Protocol

from src.domain.models.memo import Memo


class MemoRepository(Protocol):
    def list_by_user(self, user_id: str) -> list[Memo]: ...
    def get(self, memo_id: int) -> Memo | None: ...
    def add(self, memo: Memo) -> Memo: ...
    def update(self, memo: Memo) -> Memo: ...
    def delete(self, memo: Memo) -> None: ...
